# Generated by Django 5.0.6 on 2024-06-21 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_customuser_image_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='media/users/default/default_profile.jpg', null=True, upload_to='media/users/profile_images'),
        ),
    ]
