# Generated by Django 5.0.6 on 2024-06-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_alter_customuser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=models.ImageField(blank=True, default='users/default/default_profile.jpg', null=True, upload_to='users/profile_images'),
        ),
    ]
