# Generated by Django 5.0.6 on 2024-07-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_message_file_message_image_alter_message_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='users/shared/audio_files'),
        ),
    ]
